### ISSUE TITLE
OOM when calculating anomaly_score in testing phase

### ISSUE THREAD

**Issue by Howeng98** [AlessioGalluccio/FastFlow#10]
Duplicate of #9 

As title mentioned, I get OOM error when my model reach the first meta epoch test set phase in calculating anomaly score.
I encounter this error whether using resnet18, DeiT, CaiT.
Seem likes @AlessioGalluccio had try to modify calculate anomaly score into the for loop, but still have the problem.
I'm using GTX1080 8GB.
Is there have any solutions? except decrease the batch size

**Comment by AlessioGalluccio** [comment]
The batch size of this code is big, I advise reducing it if you have problems
