### ISSUE TITLE
AttributeError: Can't pickle local object '_BaseCouplingBlock.__init__.<locals>.<lambda>'

### ISSUE THREAD

**Issue by wz940216** [AlessioGalluccio/FastFlow#3]
Error in saving model
AttributeError: Can't pickle local object '_BaseCouplingBlock.__init__.<locals>.<lambda>'

in code 
train.py
    if c.save_model:
        model.to('cpu')
        save_model(model, c.modelname)
        save_weights(model, c.modelname)

**Comment by AlessioGalluccio** [comment]
That piece of code comes from https://github.com/marco-rudolph/differnet
I haven't modified it yet. Maybe you can find a solution there. Which device did you use?

**Comment by QQR1** [comment]
I encountered the same problem when saving the model, the error code is as follows :
`AttributeError: Can't pickle local object 'AllInOneBlock.__init__.<locals>.<lambda>`

**Comment by AlessioGalluccio** [comment]
Hi @QQR1, @wz940216, I modified the code in train.py from
```
save_model(model), c.modelname)
```
to
```
save_model(model.state_dict(), c.modelname)
```
I tested it and it should work. Let me know. I found the solution at this link https://github.com/pytorch/pytorch/issues/7545
Best,
Alessio
