### ISSUE TITLE
AttributeError: 'GraphINN' object has no attribute 'jacobian'

### ISSUE THREAD

**Issue by xfby2016** [AlessioGalluccio/FastFlow#6]
when I set grad_map_viz = True ， There is an error ：AttributeError: 'GraphINN' object has no attribute 'jacobian'.
It seems to have appeared in:   localization.py", line 44, in export_gradient_maps
loss = get_loss(emb, model.nf.jacobian(run_forward=False))

Any  advice? Thanks

**Comment by AlessioGalluccio** [comment]
Hi @xfby2016, thanks for your remark.
I updated the code in location.py to
```
emb, log_jac_det = model(inputs)
loss = get_loss(emb, log_jac_det)
```
The old code used an older version of the FrEIA package. It should work now. Let me know if you find other issues.
Best,
Alessio
