### ISSUE TITLE
RuntimeError: shape '[-1, 32, 262144]' is invalid for input of size 792723456

### ISSUE THREAD

**Issue by QQR1** [AlessioGalluccio/FastFlow#7]
Traceback (most recent call last):
  File "/snap/pycharm-community/261/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/261/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/hzf/QLING/code/FastFlow/main.py", line 31, in <module>
    model = train(train_loader, test_loader)
  File "/home/hzf/QLING/code/FastFlow/train.py", line 128, in train
    z_grouped = torch.cat(test_z, dim=0).view(-1, c.n_transforms_test, c.n_feat)

The error occured in this code:
       ```test_labels = np.concatenate(test_labels)
        is_anomaly = np.array([0 if l == 0 else 1 for l in test_labels])
        z_grouped = torch.cat(test_z, dim=0).view(-1, c.n_transforms_test, c.n_feat)```
I set the dataloder params as follows:
`n_transforms = 4 # number of transformations per sample in training
n_transforms_test = 32 # number of transformations per sample in testing
batch_size = 8 # `
`test_z` shape is (42, 32, 64, 96, 96)

**Comment by AlessioGalluccio** [comment]
Hi @QQR1,
Thanks for your remark.
I updated the code in location.py to
```
emb, log_jac_det = model(inputs)
loss = get_loss(emb, log_jac_det)
```
The old code used an older version of the FrEIA package. Now it should work. I tested it and I saw no errors. Let me know if you find other issues.
Best,
Alessio

**Comment by AlessioGalluccio** [comment]
Hi @QQR1 , thanks for the remark. I'll try to solve the issue as soon as possible.
Best,
Alessio

**Comment by AlessioGalluccio** [comment]
@QQR1 which feature extractor have you used? I tried to replicate your error, but with `extractor_name = "deit"` in config.py, I had no issues.
Best,
Alessio

**Comment by QQR1** [comment]
@AlessioGalluccio When I updated the code, the bug was fixed. Thank you very much
